### ISSUE TITLE
Generated Patches have 1 channel when reading 3 channel images from one JPG file

### ISSUE THREAD

**Issue by orhunguley** [CBICA/GaNDLF#100]
**Describe the bug**
This bug appears in the classification problems. If the dataset are consist of jpg files having 3 channels, but in one jpg image, the patch generator generates images as `[128x128x1]` instead of `[128x128x3]`.
**To Reproduce**
1. Go tto master branch
2. Use the config file attached and prepare the csv file based on the images I attached.
3. Run gandlf

**Expected behavior**
A runtime error regarding to the channels.

```
RuntimeError: Given groups=1, weight of size [64, 3, 3, 3], expected input[64, 1, 128, 128] to have 3 channels, but got 1 channels instead
```

**Screenshots**
![image](https://user-images.githubusercontent.com/24361544/122982406-1e7f8f80-d39b-11eb-959e-a583f65bbf36.png)
![image](https://user-images.githubusercontent.com/24361544/122982451-2ccdab80-d39b-11eb-8f82-39ffedf130b4.png)

[config_class.txt](https://github.com/CBICA/GaNDLF/files/6696690/config_class.txt)
![301004](https://user-images.githubusercontent.com/24361544/122981969-9ef1c080-d39a-11eb-892f-66981378b260.jpg)
![301005](https://user-images.githubusercontent.com/24361544/122981970-9ef1c080-d39a-11eb-90fe-bb97b1927b08.jpg)
![301006](https://user-images.githubusercontent.com/24361544/122981971-9f8a5700-d39a-11eb-91d8-c3fc17bec1c3.jpg)
![301007](https://user-images.githubusercontent.com/24361544/122981973-9f8a5700-d39a-11eb-92cd-10fc0f8ac06e.jpg)
![301000](https://user-images.githubusercontent.com/24361544/122981976-9f8a5700-d39a-11eb-8f2f-a22bee6c5f8d.jpg)
![301001](https://user-images.githubusercontent.com/24361544/122981978-9f8a5700-d39a-11eb-898d-a3d77e1a8a0e.jpg)
![301002](https://user-images.githubusercontent.com/24361544/122981981-a022ed80-d39a-11eb-9faf-f3496a4c11e6.jpg)
![301003](https://user-images.githubusercontent.com/24361544/122981982-a022ed80-d39a-11eb-9a91-53ef5a8dff3b.jpg)
ages.githubusercontent.com/24361544/122981569-31de2b00-d39a-11eb-9ba0-4872c0b1079f.png)

[mini_training_data - Copy.txt](https://github.com/CBICA/GaNDLF/files/6696721/mini_training_data.-.Copy.txt)

**GaNDLF Version**
0.0.10

**Desktop (please complete the following information):**
 - Ubuntu 20.04 WSL 2

**Comment by sarthakpati** [comment]
Hey @orhunguley,

This is a great report, and allowed me to recreate the issue perfectly. I am hoping that I can solve it quickly and put in a PR.

Cheers!

**Comment by sarthakpati** [comment]
Can you try pulling from https://github.com/sarthakpati/GaNDLF/tree/100_rgb_fix to see if this fixes your problem?

**Comment by orhunguley** [comment]
Hi Sarthak,
I got the following error with  100_rgb_fix branch:

************************************************************************************************************************************************************************
```
Traceback (most recent call last):
  File "gandlf_run", line 157, in <module>
    main()
  File "gandlf_run", line 143, in main
    reset_prev=reset_prev,
  File "/home/orhunguley/Git/GanDLF_forked/GaNDLF/GANDLF/training_manager.py", line 242, in TrainingManager
    testing_data=testingData,
  File "/home/orhunguley/Git/GanDLF_forked/GaNDLF/GANDLF/training_loop.py", line 654, in training_loop
    training_data_for_torch = ImagesFromDataFrame(training_data, params, train=True)
  File "/home/orhunguley/Git/GanDLF_forked/GaNDLF/GANDLF/data/ImagesFromDataFrame.py", line 271, in ImagesFromDataFrame
    img_resized = apply_resize(img, preprocessing_params=preprocessing)
  File "/home/orhunguley/Git/GanDLF_forked/GaNDLF/GANDLF/preprocessing.py", line 87, in apply_resize
    resize_image_resolution(input, preprocessing_params["resize"]),
  File "/home/orhunguley/Git/GanDLF_forked/GaNDLF/GANDLF/preprocessing.py", line 77, in resize_image_resolution
    outputSpacing[i] = outputSpacing[i] * (inputSize[i] / output_size[i])
IndexError: index 2 is out of bounds for axis 0 with size 2
```


************************************************************************************************************************************************************************

**Comment by sarthakpati** [comment]
Can you try by disabling resizing?

**Comment by orhunguley** [comment]
Hi @sarthakpati, 
Thanks, with setting [128, 128] the issue is solved now!
