### ISSUE TITLE
Multi-batch training for regression/classification is failing

### ISSUE THREAD

**Issue by sarthakpati** [CBICA/GaNDLF#105]
**Describe the bug**
The ground truth shape is inconsistent

**To Reproduce**
1. Train for regression/classification with multiple batches
2. See error at L159 of `GANDLF.training_loop`

**Expected behavior**
This error should not happen.

**Screenshots**
N.A.

**GaNDLF Version**
0.0.10

**Desktop (please complete the following information):**
N.A.

**Additional context**
N.A.

**Comment by orhunguley** [comment]
Hi @sarthakpati , I also encountered this error end fix it by changing that line to:

`label = label.reshape(image.shape[0], len(params["value_keys"]))`

**Comment by sarthakpati** [comment]
What is the rationale behind using `image.shape[0]`?

**Comment by orhunguley** [comment]
Because the last batch coming from data loader is not equal to batch size, but it is equal to the number of remaining images. For example I was getting the error because in the last iteration the batch size was 43, but it was trying to reshape it assuming that it is 64.

**Comment by sarthakpati** [comment]
I understand. Would the commit https://github.com/CBICA/GaNDLF/pull/106/commits/fa70a180527818634054474bad1e521517279918 fix your issue as well? I tried it with different scenarios and it seemed to work as expected.

**Comment by orhunguley** [comment]
Hi @sarthakpati , yes it fixed the issue as well. Thanks!
