### ISSUE TITLE
Error in gandlf_collectStats

### ISSUE THREAD

**Issue by bahetibhakti** [CBICA/GaNDLF#115]
**Describe the bug**
I am working in WSL2 and followed all installation instructions. 
I was able to run the file "gandlf_run" on CUDA device and some folders are generated in the Output directory.
However I am getting the following error while running the "gandlf_collectStats" 
(GaNDLF Version: 0.0.9)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/6376680/123638806-96134b80-d7ed-11eb-8805-6c7db37a2963.png)

**Comment by sarthakpati** [comment]
Hmm, I don't think this is the correct usage of `gandlf_collectStats`. Looking at the help, you need to pass the input directory (which contains the testing and validation models) and the output directory, where the stats and plots get saved:

```powershell
(C:\Projects\GANDLF\venv) PS C:\Projects\GANDLF> python .\gandlf_collectStats -h
usage: GANDLF_CollectCSV [-h] -inputDir INPUTDIR -outputDir OUTPUTDIR

Collect statistics from different testing/validation combinations from output directory.

Contact: software@cbica.upenn.edu

This program is NOT FDA/CE approved and NOT intended for clinical use.
Copyright (c) 2021 University of Pennsylvania. All rights reserved.

optional arguments:
  -h, --help            show this help message and exit
  -inputDir INPUTDIR    Input directory which contains testing and validation models
  -outputDir OUTPUTDIR  Output directory to save stats and plot
```

**Comment by sarthakpati** [comment]
Closing this, for now. Please re-open/comment if you face issues!

**Comment by sarthakpati** [comment]
Now that I see the documentation, it needs to be revised.
