### ISSUE TITLE
Using gandlf in windows

### ISSUE THREAD

**Issue by bahetibhakti** [CBICA/GaNDLF#116]
I am trying to install gandlf in windows by following instructions on https://cbica.github.io/GaNDLF/extending 
I am getting an error while doing "conda install -c conda-forge gandlf -y"

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/6376680/123639756-80525600-d7ee-11eb-8e99-68a4058e2a9a.png)

Can you please help me with this?

**Comment by sarthakpati** [comment]
Can you try the following:

```powershell
git clone https://github.com/CBICA/GaNDLF.git
cd GaNDLF
conda create -p ./venv python=3.7 -y
conda activate ./venv
conda install -c conda-forge mamba -y # allows for faster dependency solving
conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch
conda install -c sdvillal openslide -y
pip install -e .
```

**Comment by bahetibhakti** [comment]
I tried new installation with above commands.
Getting error in "pip install -e ."

![image](https://user-images.githubusercontent.com/6376680/123706023-b6ff8f00-d835-11eb-814f-906db4c2deb1.png)

![image](https://user-images.githubusercontent.com/6376680/123706070-cd0d4f80-d835-11eb-9e6f-bfd8d8104dd7.png)

**Comment by sarthakpati** [comment]
Can you install MSVC 14+ from http://visualstudio.microsoft.com/visual-cpp-build-tools and re-try?

**Comment by bahetibhakti** [comment]
It worked and I am able to import Gandlf.
Thanks!

**Comment by sarthakpati** [comment]
Can you put in a PR adding this instruction? Thank you!
