### ISSUE TITLE
Moving to torchmetrics for handling metrics

### ISSUE THREAD

**Issue by Geeks-Sid** [CBICA/GaNDLF#123]
**Is your feature request related to a problem? Please describe.**
Instead of implementing all the metrics, why not use [torchmetrics](https://torchmetrics.readthedocs.io/en/latest/) ?

**Comment by sarthakpati** [comment]
Brilliant. Let's do this.

**Comment by sarthakpati** [comment]
Just realized that torchmetrics is already getting used for F1. Now, we just need to add more metrics. Closing this out to add a separate feature request for new metrics.
