### ISSUE TITLE
Error In Classification Tasks -- `perform_sanity_check_on_subject` Function

### ISSUE THREAD

**Issue by orhunguley** [CBICA/GaNDLF#147]
**Describe the bug**
When running GaNDLF, error occured in  638th line of utils.py file. That is due to subject[str(key)] = "NA" and it does not have "path" key value since it is just string.

**To Reproduce**
1. Run GaNDLF with the configuration I attached.
2. Error should occur before the training started.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/24361544/126798290-e34590c5-acaa-43bc-be2e-b6f677d61973.png)

**GaNDLF Version**
11

**Desktop (please complete the following information):**
 - Linux WSL 20.04

**Additional context**
[mini_training_data_2.txt](https://github.com/CBICA/GaNDLF/files/6869487/mini_training_data_2.txt)
[config_classification.txt](https://github.com/CBICA/GaNDLF/files/6869488/config_classification.txt)

**Comment by sarthakpati** [comment]
Can you insert the following line in L634 in utils.py and post the output:

```python
print(list_for_comparison)
```

**Comment by orhunguley** [comment]
Here it is:

------List of Comparison------
[1, 'label']
------------------------------

**Comment by sarthakpati** [comment]
There is something weird going on, because the CSV only contains the following and no label:

```
SubjectID,Channel_0,ValueToPredict
```

Let me see if I can reproduce this on my end.
