### ISSUE TITLE
Error In Classification due to a bug in get_loss_and_metrics()

### ISSUE THREAD

**Issue by orhunguley** [CBICA/GaNDLF#156]
**Describe the bug**
New version of "get_loss_and_metrics" function is not covering classification tasks. 
line 494 --> "if len(predicted) > 1:" statement is designed for sdnet-style archs but for classification tasks, the len(pred) is equal to the batch size, which is the case most of the time for classification.

**To Reproduce**
1. run GaNDLF for classification tasks
2. You can use the config file I attached.

**Expected behavior**
The following error occures.
![image](https://user-images.githubusercontent.com/24361544/127570316-19a1da95-1a36-4912-8cee-5cebdbaa62bc.png)
That is due to line 496 --> loss_seg = loss_function(predicted[0], ground_truth.squeeze(-1), params) uses only the prediction, but the ground truth has the shape of batch_size.

**Screenshots**

**GaNDLF Version**
Version information is found on Help > About
0.11

**Desktop (please complete the following information):**
 - Linux WSL Ubuntu 20.04
[config_classification.txt](https://github.com/CBICA/GaNDLF/files/6903853/config_classification.txt)

**Comment by sarthakpati** [comment]
Check if this fixes it? https://github.com/sarthakpati/GaNDLF/commit/80c3a3b2b75caaa469ea80a8cd0f6c238ad92b23

Branch: https://github.com/sarthakpati/GaNDLF/commits/156_classification_fix

**Comment by orhunguley** [comment]
> Check if this fixes it? [sarthakpati@80c3a3b](https://github.com/sarthakpati/GaNDLF/commit/80c3a3b2b75caaa469ea80a8cd0f6c238ad92b23)
> 
> Branch: https://github.com/sarthakpati/GaNDLF/commits/156_classification_fix

yeap, it fixed the bug. thanks!
