### ISSUE TITLE
Imagenet weights for GANDLF vgg/resnet etc for 2D images

### ISSUE THREAD

**Issue by Geeks-Sid** [CBICA/GaNDLF#26]
**Is your feature request related to a problem? Please describe.**
It would be great to have pretrained imagenet weights in GANDLF for 2D images

**Describe the solution you'd like**
in the .yaml file, it would be great to have imagenet option set to true to work with pretrained weights if need rises.

**Describe alternatives you've considered**

**Additional context**
https://pytorch.org/vision/0.8/_modules/torchvision/models/vgg.html

**Comment by sarthakpati** [comment]
Is it okay if I integrated this directly into the refactor branch?

**Comment by sarthakpati** [comment]
Can be closed.
