### ISSUE TITLE
Missing parameters in sample configs

### ISSUE THREAD

**Issue by Karol-G** [CBICA/GaNDLF#29]
Hi,

the sample configs don't seem to be up to date. Would probably be a good idea to check them all ;)
I got another error from my problem over in #27.
This time it is:

```
Using default folds for testing split:  -5
Using default folds for validation split:  -5
Number of channels :  3
Traceback (most recent call last):
  File "gandlf_run", line 75, in <module>
    main()
  File "gandlf_run", line 70, in main
    TrainingManager(dataframe=data_full, headers = headers, outputDir=model_path, parameters=parameters, device=device, reset_prev = reset_prev)
  File "/content/GaNDLF-refactor/GANDLF/training_manager.py", line 146, in TrainingManager
    device=device, params=parameters, testing_data=testingData)
  File "/content/GaNDLF-refactor/GANDLF/training_loop.py", line 357, in training_loop
    train=True,
  File "/content/GaNDLF-refactor/GANDLF/data/ImagesFromDataFrame.py", line 240, in ImagesFromDataFrame
    augmentation_list.append(global_preprocessing_dict['crop_external_zero_planes'](patch_size))
  File "/content/GaNDLF-refactor/GANDLF/data/ImagesFromDataFrame.py", line 71, in crop_external_zero_planes
    return CropExternalZeroplanes(patch_size=patch_size)
TypeError: __init__() missing 1 required positional argument: 'psize'
```

So the psize parameter is missing.

Best
Karol

**Comment by sarthakpati** [comment]
Hey Karol,

I believe this is fixed in the refactor branch. 😄 

https://github.com/CBICA/GaNDLF/blob/refactor/GANDLF/data/ImagesFromDataFrame.py#L71

Cheers!

**Comment by Karol-G** [comment]
This is actually the refactor branch^^
https://github.com/CBICA/GaNDLF/blob/a5a7d9c945edb003d02f50dc3a69eb830d564247/GANDLF/preprocessing.py#L179
psize is still in the __init__() here.
There are about 20 more places in the code where psize is assigned or checked, but I don't know if that is relevant to the problem.

Best
Karol

**Comment by sarthakpati** [comment]
Got it. I have made fixes in the training side, while @Geeks-Sid is working on the inference part.

**Comment by Karol-G** [comment]
Thanks, the error is gone now. :)

**Comment by sarthakpati** [comment]
Awesome! Glad we are able to keep this working with a short turnaround!

**Comment by Karol-G** [comment]
There are actually still some psize errors when I try to run inference. But training is working :)

**Comment by sarthakpati** [comment]
Yup, inference is not yet complete (this is on @Geeks-Sid's plate at this moment).

**Comment by sarthakpati** [comment]
I believe this should now be fixed. @Karol-G please comment/re-open if you see issues.
