### ISSUE TITLE
Inference of classification task on unseen data

### ISSUE THREAD

**Issue by bahetibhakti** [CBICA/GaNDLF#360]
**Describe the bug**
Hi, I am running a classification experiment (of brain MRI scans)using GaNDLF. After the model is trained, I want to evaluate the performance on some new data for which I do not have labels. When I try to run gandlf_run for inference by providing a .csv with subject Id and path of four modalities, I get an error: 

![Error_without_having_valuetopredict_column](https://user-images.githubusercontent.com/6376680/159083407-982944e6-1f6c-4688-b691-8ce516e5cdfc.png)

Can you please help me on how to obtain the label predictions when I don't have groundtruth labels for the test data?

**Comment by sarthakpati** [comment]
Hey @bahetibhakti, can you check if https://github.com/CBICA/GaNDLF/pull/363 fixes the issue?

**Comment by bahetibhakti** [comment]
I am getting following error.
![without_column_name](https://user-images.githubusercontent.com/6376680/159363452-d7cd514f-991a-4ace-aed4-7ea7461cbccd.png)

I also tried with keeping 'valuetopredict' column name without any data in the column. But then returns different error.

**Comment by sarthakpati** [comment]
Try again?

**Comment by bahetibhakti** [comment]
I am getting same error gain...

**Comment by sarthakpati** [comment]
Weird; what's L247 for `GANDLF.compute.forward_pass.py`?

**Comment by bahetibhakti** [comment]
Thanks Sarthak. This is resolved now.
