### ISSUE TITLE
Weight calculation for classification

### ISSUE THREAD

**Issue by Geeks-Sid** [CBICA/GaNDLF#362]
**Is your feature request related to a problem? Please describe.**
The weight calculation for classification can be done in seconds instead of iterating over an entire dataloader.

**Describe the solution you'd like**
We can create classification weights through simple dataframe manipulation.

**Describe alternatives you've considered**

**Additional context**

**Comment by sarthakpati** [comment]
Can you give the specific code example to perform the calculation from `data_frame["valuetopredict"]`?

**Comment by sarthakpati** [comment]
This is fixed with #365
