### ISSUE TITLE
Code re-organization

### ISSUE THREAD

**Issue by tchaton** [CBICA/GaNDLF#40]
**Is your feature request related to a problem? Please describe.**

This framework looks great, but it seems the code internally is pretty messy and hard to extend.

Have a look at Lightning Flash: https://github.com/PyTorchLightning/lightning-flash/blob/master/flash_examples/finetuning/object_detection.py#L23.

It might help to re-organize the code and make the tasks simpler to extends.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sarthakpati** [comment]
Thank you for your input. I and @Geeks-Sid absolutely agree with you. We have been working on refactoring the entire codebase. Please see https://github.com/CBICA/GaNDLF/tree/refactor and provide feedback! 😄
