### ISSUE TITLE
Add ability to handle high compression file formats (e.g., jpg) for segmentation output

### ISSUE THREAD

**Issue by sarthakpati** [CBICA/GaNDLF#431]
**Is your feature request related to a problem? Please describe.**
Currently, writing masks are written as 16-bit images at inference time: 
https://github.com/CBICA/GaNDLF/blob/f6d26038a9d6203941748e43a593663594a3b0c0/GANDLF/compute/forward_pass.py#L330

However, this produces blank images because only JPG-200 supports 16-bit pixels properly [[ref](https://users.wfu.edu/yipcw/atg/jpeg2000/)].

**Describe the solutions you'd like**
There are a few ways around this problem:
- do not support jpg output at all, since it seems like it could be an issue if a system does not have the appropriate jpeg2000 libraries installed, and if one of `[".jpg", ".jpeg"]` (or more) are detected in the following function, return `".png"`:
https://github.com/CBICA/GaNDLF/blob/f6d26038a9d6203941748e43a593663594a3b0c0/GANDLF/utils/generic.py#L71
- if jpg needs to be written, use `tifffile` (which has internal support for JPEG2000 standard since version `2022.2.2`) to write image instead of the default (i.e., `SimpleITK`)
- if jpg needs to be written, cast image to 8-bit, but ONLY if jpg is detected:
https://github.com/CBICA/GaNDLF/blob/f6d26038a9d6203941748e43a593663594a3b0c0/GANDLF/compute/forward_pass.py#L330

**Describe alternatives you've considered**
Easiest would be the first choice above. Second would be the more robust solution but take more time to implement, and the last would be somewhere in the middle but prone to breakage for cases with large number of labels.

**Additional context**
N.A.

**Comment by sarthakpati** [comment]
Tracking solution in https://github.com/sarthakpati/GaNDLF/tree/431_write_jpeg2000

@Geeks-Sid can you please try what you were doing using that branch and let me know if it works?

**Comment by Geeks-Sid** [comment]
Thanks, Looking into it.
