### ISSUE TITLE
Add attention maps

### ISSUE THREAD

**Issue by sarthakpati** [CBICA/GaNDLF#5]
**Is your feature request related to a problem? Please describe.**
Interpretability in DL training is critical and would be very nice to have in GaNDLF.

**Describe the solution you'd like**
Integrate [M3d-Cam](https://github.com/MECLabTUDA/M3d-Cam) into the training/inference process.

**Describe alternatives you've considered**
Open to other suggestions.

**Additional context**
Also requested by @gastouna

**Comment by Karol-G** [comment]
Hi,

I successfully integraded medcam into the validation section of the training already.
Currently there are probably some issues with assembling the attention patches with the `torchio.inference.GridAggregator`, but I am not entirely sure. These issues could also simply originate from the fact that the model is untrained.
Do you have a fully trained segmentation dataset, model and config yaml at hand that you could send me?

Best
Karol

**Comment by sarthakpati** [comment]
> I successfully integraded medcam into the validation section of the training already.

Awesome news!!!

> These issues could also simply originate from the fact that the model is untrained.

Could you elaborate? I think the `torchio.inference.GridAggregator` does not care if a model is completely trained or not, as long as it is fed patch locations [[ref](https://github.com/CBICA/GaNDLF/blob/refactor/GANDLF/training_loop.py#L276)].

> Do you have a fully trained 2D segmentation dataset, model and config yaml at hand that you could send me?

I do not have any such example on hand, perhaps @Geeks-Sid does?

**Comment by Karol-G** [comment]
Here is an example of the attention superimposed over the original image input:

![attention_map](https://user-images.githubusercontent.com/3471895/113307605-9cd11600-9305-11eb-830a-885df2f31263.png)

The model is of course not able to learn from just a few images what it should pay attention to, so it is more or less random. However, you can clearly see borders and different normalizations. My hope is that this will go away when the model is trained. I integrated medcam into the nnUNet for example as well which is also patch-based and had no such problems (but I only tested on the finished models). But it could also be the case that there is some problem with normalization or interpolation.

**Comment by sarthakpati** [comment]
Ah okay. That actually looks great! I'll ping @Geeks-Sid if he has a fully trained model.

**Comment by sarthakpati** [comment]
Fixed by #51
